### ISSUE TITLE
CSS for links needs changing

### ISSUE THREAD

**Issue by ianmcn** [superawesomeme/aardvark#3]
The current styles means that links are exactly the same colour and style as paragraph text, giving no indication that they are links:
```css
html a,body a,html a:visited,body a:visited {
color:#333;
}
```
and
```css
html,body {
font-family: Verdana, Geneva, sans-serif !important;
background:[[setting:backcolor]] url([[setting:backimage]]) center top [[setting:backposition]] !important;
color:#333;
margin:0;
padding:0;
}
```

In both cases the color is #333. Maybe this could be a configurable value? Either way, the default should surely make it possible to see what are links?
